export const PLANET_INFO = {
    Sun: {
        description: "The Sun is a G-type main-sequence star (G2V) based on its spectral class. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core. The Sun currently fuses approximately 600 million tons of hydrogen into helium every second, converting 4 million tons of matter into energy. This energy, which can take between 10,000 and 170,000 years to escape the core, is the source of all life and weather on Earth. The solar atmosphere consists of the photosphere, chromosphere, and the transition region, leading to the corona, which paradoxically is much hotter than the surface.",
        stats: {
            "Surface Gravity": "274.0 m/s²",
            "Escape Velocity": "617.7 km/s",
            "Luminosity": "3.828 × 10²⁶ W",
            "Core Temp": "15.7 Million K",
            "Spectral Type": "G2V",
            "Rotation Period": "25.05 Days"
        },
        composition: { Hydrogen: "73.46%", Helium: "24.85%", Oxygen: "0.77%", Carbon: "0.29%" },
        color: '#FFCC00',
        mechanics: { eccentricity: "N/A", inclination: "7.25° to Ecliptic", velocity: "220 km/s (Galactic)" },
        class: "G2V Star"
    },
    Mercury: {
        description: "Mercury is the smallest planet in the Solar System and the closest to the Sun. Due to its lack of a substantial atmosphere to retain heat, it has the most extreme temperature variations in the solar system, ranging from 100 K at night to 700 K during the day. Its surface is heavily cratered and similar in appearance to the Moon, indicating that it has been geologically inactive for billions of years. Mercury is tidally locked with the Sun in a 3:2 spin-orbit resonance, meaning it rotates three times for every two orbits around the Sun.",
        stats: {
            "Surface Gravity": "3.7 m/s²",
            "Surface Pressure": "10⁻¹⁴ bar",
            "Magnetic Field": "1.1% of Earth's",
            "Mean Radius": "2,439.7 km",
            "Density": "5.427 g/cm³",
            "Axial Tilt": "0.034°"
        },
        composition: { Iron: "70% (Core)", Silicates: "30% (Crust)", Oxygen: "42%", Sodium: "29%" },
        color: '#A8A8A8',
        mechanics: { eccentricity: "0.2056", inclination: "7.005°", velocity: "47.36 km/s" },
        class: "Terrestrial Planet"
    },
    Venus: {
        description: "Venus is often described as Earth's sister planet due to their similar size and mass, but it is radically different in every other way. It has the densest atmosphere of the four terrestrial planets, consisting of more than 96% carbon dioxide. The atmospheric pressure at the surface is 92 times that of Earth. Venus is shrouded by an opaque layer of highly reflective clouds of sulfuric acid, preventing its surface from being seen from space in visible light. It may have had water oceans in the past, but these would have vaporized as the temperature rose due to a runaway greenhouse effect.",
        stats: {
            "Surface Gravity": "8.87 m/s²",
            "Surface Pressure": "92 bar",
            "Surface Temp": "464°C (Mean)",
            "Mean Radius": "6,051.8 km",
            "Density": "5.243 g/cm³",
            "Axial Tilt": "177.3° (Retrograde)"
        },
        composition: { "Carbon Dioxide": "96.5%", Nitrogen: "3.5%", "Sulfur Dioxide": "0.015%", Argon: "0.007%" },
        color: '#E3BB76',
        mechanics: { eccentricity: "0.0067", inclination: "3.394°", velocity: "35.02 km/s" },
        class: "Terrestrial Planet"
    },
    Earth: {
        description: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being an ocean world; the only one in the Solar System known to harbor liquid surface water. Earth's lithosphere is divided into several rigid tectonic plates that migrate across the surface over periods of many millions of years. Earth's atmosphere consists mostly of nitrogen and oxygen, and it has a powerful magnetic field generated by its active iron core, which shields the planet from damaging solar radiation.",
        stats: {
            "Surface Gravity": "9.806 m/s²",
            "Surface Pressure": "1.013 bar",
            "Albedo": "0.306",
            "Mean Radius": "6,371.0 km",
            "Density": "5.514 g/cm³",
            "Axial Tilt": "23.44°"
        },
        composition: { Nitrogen: "78.08%", Oxygen: "20.95%", Argon: "0.93%", "Carbon Dioxide": "0.04%" },
        color: '#2271B3',
        mechanics: { eccentricity: "0.0167", inclination: "0.000° (Ref)", velocity: "29.78 km/s" },
        class: "Terrestrial Planet"
    },
    Mars: {
        description: "Mars is a terrestrial planet with a thin atmosphere, having surface features reminiscent both of the impact craters of the Moon and the valleys, deserts, and polar ice caps of Earth. It is home to Olympus Mons, the largest volcano and highest known mountain on any planet in the Solar System, and Valles Marineris, one of the largest canyons. The smooth Borealis basin in the Northern Hemisphere covers 40% of the planet and may be a giant impact feature. Mars has two moons, Phobos and Deimos, which are small and irregularly shaped.",
        stats: {
            "Surface Gravity": "3.721 m/s²",
            "Surface Pressure": "0.006 bar",
            "Day Length": "24h 37m",
            "Mean Radius": "3,389.5 km",
            "Density": "3.933 g/cm³",
            "Axial Tilt": "25.19°"
        },
        composition: { "Carbon Dioxide": "95.3%", Nitrogen: "2.7%", Argon: "1.6%", Oxygen: "0.13%" },
        color: '#E27B58',
        mechanics: { eccentricity: "0.0934", inclination: "1.850°", velocity: "24.07 km/s" },
        class: "Terrestrial Planet"
    },
    Jupiter: {
        description: "Jupiter is the largest planet in the Solar System, a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined. It is primarily composed of hydrogen, but helium constitutes one-fourth of its mass and one-tenth of its volume. It probably has a rocky core of heavier elements, but like the other giant planets, Jupiter lacks a well-defined solid surface. The Great Red Spot, a giant storm known to have existed since at least the 17th century, is visible through even small telescopes.",
        stats: {
            "Surface Gravity": "24.79 m/s²",
            "Surface Pressure": ">100 bar",
            "Magnetic Moment": "18,000x Earth",
            "Mean Radius": "69,911 km",
            "Density": "1.326 g/cm³",
            "Axial Tilt": "3.13°"
        },
        composition: { Hydrogen: "89.8%", Helium: "10.1%", Methane: "0.3%", Ammonia: "0.02%" },
        color: '#D39C7E',
        mechanics: { eccentricity: "0.0489", inclination: "1.303°", velocity: "13.07 km/s" },
        class: "Gas Giant"
    },
    Saturn: {
        description: "Saturn is a gas giant with an average radius of about nine times that of Earth. Although it has only one-eighth the average density of Earth, with its larger volume, Saturn is over 95 times more massive. Saturn's interior is most likely composed of a core of iron–nickel and rock (silicon and oxygen compounds). This core is surrounded by a deep layer of metallic hydrogen, an intermediate layer of liquid hydrogen and liquid helium, and finally, a gaseous outer layer.",
        stats: {
            "Surface Gravity": "10.44 m/s²",
            "Wind Speed": "1,800 km/h",
            "Ring Count": "7 Main Groups",
            "Mean Radius": "58,232 km",
            "Density": "0.687 g/cm³",
            "Axial Tilt": "26.73°"
        },
        composition: { Hydrogen: "96.3%", Helium: "3.2%", Methane: "0.45%", Ammonia: "0.01%" },
        color: '#C5AB6E',
        mechanics: { eccentricity: "0.0565", inclination: "2.485°", velocity: "9.68 km/s" },
        class: "Gas Giant"
    },
    Uranus: {
        description: "Uranus is an ice giant, meaning it has a higher proportion of 'ices' such as water, ammonia, and methane, along with traces of hydrocarbons. It has the coldest planetary atmosphere in the Solar System, with a minimum temperature of 49 K. It has a complex, layered cloud structure; water is thought to make up the lowest clouds, and methane the uppermost layer. The interior of Uranus is mainly composed of ices and rock.",
        stats: {
            "Surface Gravity": "8.69 m/s²",
            "Obliquity": "97.77° (Sideways)",
            "Magnetic Tilt": "59°",
            "Mean Radius": "25,362 km",
            "Density": "1.270 g/cm³",
            "Sidereal Orbit": "84.02 yrs"
        },
        composition: { Hydrogen: "82.5%", Helium: "15.2%", Methane: "2.3%", Deuterium: "0.01%" },
        color: '#BBE1E4',
        mechanics: { eccentricity: "0.0472", inclination: "0.772°", velocity: "6.80 km/s" },
        class: "Ice Giant"
    },
    Neptune: {
        description: "Neptune is the most distant known solar planet and the fourth-largest planet by diameter. It is 17 times the mass of Earth and slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere. The planet orbits the Sun once every 164.8 years at an average distance of 30.1 AU. Neptune is not visible to the unaided eye and is the only planet in the Solar System found by mathematical prediction rather than by empirical observation.",
        stats: {
            "Surface Gravity": "11.15 m/s²",
            "Wind Speed": "2,100 km/h",
            "Heat Flux": "2.6x Absorbed",
            "Mean Radius": "24,622 km",
            "Density": "1.638 g/cm³",
            "Axial Tilt": "28.32°"
        },
        composition: { Hydrogen: "80%", Helium: "19%", Methane: "1.5%", Ethane: "0.0001%" },
        color: '#6081FF',
        mechanics: { eccentricity: "0.0113", inclination: "1.767°", velocity: "5.43 km/s" },
        class: "Ice Giant"
    },
    Pluto: {
        description: "Pluto is a dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It was the first and largest Kuiper belt object to be discovered. Pluto is the ninth-largest and tenth-most-massive known object directly orbiting the Sun. It is the largest known trans-Neptunian object by volume but is less massive than Eris. Like other Kuiper belt objects, Pluto is primarily made of ice and rock and is relatively small—one-sixth the mass of the Moon and one-third its volume.",
        stats: {
            "Surface Gravity": "0.62 m/s²",
            "Surface Pressure": "10 μbar",
            "Atmosphere": "Nitrogen / Methane",
            "Mean Radius": "1,188.3 km",
            "Density": "1.854 g/cm³",
            "Axial Tilt": "122.53°"
        },
        composition: { "Nitrogen Ice": "98%", Methane: "0.5%", "Carbon Monoxide": "0.5%", Water: "Traces" },
        color: '#968570',
        mechanics: { eccentricity: "0.2488", inclination: "17.16°", velocity: "4.74 km/s" },
        class: "Dwarf Planet"
    }
};

export const PLANET_CONFIG = [
    { name: 'Sun', dist: 0, size: 8, speed: 0 },
    { name: 'Mercury', dist: 28, size: 1.2, speed: 0.9 },
    { name: 'Venus', dist: 45, size: 2.1, speed: 0.7 },
    {
        name: 'Earth', dist: 65, size: 2.2, speed: 0.55, moons: [
            { name: 'Luna', size: 0.5, dist: 4, speed: 2, color: '#aaaaaa' }
        ]
    },
    { name: 'Mars', dist: 85, size: 1.8, speed: 0.45 },
    {
        name: 'Jupiter', dist: 120, size: 5.5, speed: 0.25, moons: [
            { name: 'Io', size: 0.4, dist: 8, speed: 3, color: '#ffffaa' },
            { name: 'Europa', size: 0.35, dist: 10, speed: 2.2, color: '#ffffff' },
            { name: 'Ganymede', size: 0.6, dist: 12, speed: 1.5, color: '#aaaaaa' },
            { name: 'Callisto', size: 0.55, dist: 15, speed: 1, color: '#888888' }
        ]
    },
    {
        name: 'Saturn', dist: 160, size: 4.8, speed: 0.18, moons: [
            { name: 'Titan', size: 0.7, dist: 10, speed: 1.2, color: '#ffcc66' }
        ]
    },
    { name: 'Uranus', dist: 200, size: 3.2, speed: 0.12 },
    { name: 'Neptune', dist: 235, size: 3.1, speed: 0.09 },
    { name: 'Pluto', dist: 265, size: 0.8, speed: 0.06 }
];

export const MISSION_DATA = [
    { name: 'Voyager 1', color: '#ff4444', path: [[0, 0, 0], [40, 20, 50], [90, 10, 120], [180, 5, 250], [300, 0, 400]], size: 1.5 },
    { name: 'Juno', color: '#44ff44', path: [[0, 0, 0], [10, 50, 20], [80, 20, 80], [120, 5, 120]], size: 1.2 },
    { name: 'New Horizons', color: '#4444ff', path: [[0, 0, 0], [150, 5, 150], [280, 2, 280], [350, 0, 400]], size: 1.0 }
];
